
---
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Copy backend dist files web server
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: Install Node
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
- name: Build Node
  become: true    
  shell: |
    cd /home/ubuntu/backend
    npm run build
- name: Start PM2
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start